
on:
  push:
    branches:
      - main

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1.18
      - run: scala-cli publish . --version "0.0.1" --secret-key-password "env:PGP_PASSPHRASE" --secret-key "env:PGP_SECRET"
