
on:
  push:
    branches: [main]
    tags: ["**"]

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1.18
      - name: Import signing key
        run: |
          echo "$PGP_SECRET" | base64 -di > /tmp/signing-key.gpg
      - run: |
          scala-cli publish . --scala 2.13.10 --compute-version "git:tag" --secret-key file:/tmp/signing-key.gpg --secret-key-password "env:PGP_PASSPHRASE"
