
on:
  push:
    branches:
      - main

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1.18
      - name: Import signing key
        if: env.PGP_SECRET != '' && env.PGP_PASSPHRASE == ''
        run: echo $PGP_SECRET | base64 -di | gpg --import
      # - run: scala-cli publish . --version "0.0.1" --secret-key-password "env:PGP_PASSPHRASE"
